


# NumPy

## Trabajo práctico 5

### 1 Creando arrays

- Crear un arreglo que represente 64 subdivisiones en el rango -1.3 a 2.5.
- Generar un arreglo de largo $3n$ con el patrón cíclico 1, 2, 3, es decir `[1,2,3,1,2,3,1...]`.
- Crear un arreglo con los 20 primeros números enteros impares.
- Crear un arreglo de 10 x 10 con ceros, y luego modificarlos para que todos sus bordes contengan 1.





In [5]:
import numpy as np
A=np.linspace(-1,3.5,64)
A

array([-1.        , -0.92857143, -0.85714286, -0.78571429, -0.71428571,
       -0.64285714, -0.57142857, -0.5       , -0.42857143, -0.35714286,
       -0.28571429, -0.21428571, -0.14285714, -0.07142857,  0.        ,
        0.07142857,  0.14285714,  0.21428571,  0.28571429,  0.35714286,
        0.42857143,  0.5       ,  0.57142857,  0.64285714,  0.71428571,
        0.78571429,  0.85714286,  0.92857143,  1.        ,  1.07142857,
        1.14285714,  1.21428571,  1.28571429,  1.35714286,  1.42857143,
        1.5       ,  1.57142857,  1.64285714,  1.71428571,  1.78571429,
        1.85714286,  1.92857143,  2.        ,  2.07142857,  2.14285714,
        2.21428571,  2.28571429,  2.35714286,  2.42857143,  2.5       ,
        2.57142857,  2.64285714,  2.71428571,  2.78571429,  2.85714286,
        2.92857143,  3.        ,  3.07142857,  3.14285714,  3.21428571,
        3.28571429,  3.35714286,  3.42857143,  3.5       ])

In [6]:
n=4
B=np.arange(3 * n) % 3 + 1
B

array([1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [20]:
B=np.zeros((10,10))
B[0,:]=1
B[:,0]=1
B[9,:]=1
B[:,9]=1
B

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

### 2 Operando con arrays
- Generere un array de 10 x 3 de números aleatorios (en el rango [0,1]). Por cada fila, encuentre el número más cercano a 0.5.
- Construya con Numpy la siguiente matriz
\begin{equation*}
\mathbf{A} =  \begin{pmatrix}
0 & 1 & 3 \\
0 & 0 & -2\\
0 & 0 & 0
\end{pmatrix}
\end{equation*}
y muestre que es *nilpotente de orden 3*, esto es:
$$
\mathbf{A}^3 = 0.
$$

In [40]:
A=np.random.rand(10, 3)
print(A)
B=np.zeros(A.shape)
B[:,:]=0.5
print(B)
C=A-B
print(C)
C=np.abs(C)
min=C.argmin()
A=A.ravel()
print('El minimo es: ', A[min])


[[0.73937734 0.44230264 0.38484487]
 [0.21830795 0.78670929 0.64557282]
 [0.75671342 0.46063984 0.68126087]
 [0.40721372 0.19358449 0.14195706]
 [0.29086063 0.30222558 0.28180764]
 [0.9702725  0.24874964 0.2786723 ]
 [0.82749373 0.77103436 0.60407109]
 [0.10593497 0.23761905 0.19581206]
 [0.61323168 0.01958033 0.69514237]
 [0.63638659 0.67973361 0.98660718]]
[[0.5 0.5 0.5]
 [0.5 0.5 0.5]
 [0.5 0.5 0.5]
 [0.5 0.5 0.5]
 [0.5 0.5 0.5]
 [0.5 0.5 0.5]
 [0.5 0.5 0.5]
 [0.5 0.5 0.5]
 [0.5 0.5 0.5]
 [0.5 0.5 0.5]]
[[ 0.23937734 -0.05769736 -0.11515513]
 [-0.28169205  0.28670929  0.14557282]
 [ 0.25671342 -0.03936016  0.18126087]
 [-0.09278628 -0.30641551 -0.35804294]
 [-0.20913937 -0.19777442 -0.21819236]
 [ 0.4702725  -0.25125036 -0.2213277 ]
 [ 0.32749373  0.27103436  0.10407109]
 [-0.39406503 -0.26238095 -0.30418794]
 [ 0.11323168 -0.48041967  0.19514237]
 [ 0.13638659  0.17973361  0.48660718]]
El minimo es:  0.46063984124944235


In [45]:
A=np.array([[0,1,3],[0,0,-2],[0,0,0]])
B=A @ A @ A
B


array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

### 3 `meshgrid`

Suponga que tenemos una grilla de 101x101 puntos en un plano, formando un arreglo cuadrado. Las coordenadas de estos puntos van de -10 a 10 cm en la dirección $x$ y de -10 a 10 cm en la dirección $y$ (esto produce que el punto central de la grilla tenga coordenadas $(x,y)=(0, 0)$). Suponiendo que el plano donde está contenida la grilla posee coordenada $z$ = 100 cm, calcule la distancia de todos los puntos al origen.

Ayuda: vea la documentación de la función `meshgrid`.